### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by Newbb1** [Nexuist/CoinMarketCapAPI#12] opened 2017-04-22 00:29 UTC
Error message when you try to contact the server.

**Comment by mandelmonkey** [comment] 2017-04-22 02:56
Yes same here, if you could take a look soon that would be great

**Comment by NarubyRiverlione** [comment] 2017-04-22 14:21
The problem is parsing the Banksys coin because it's symbol contain '@' .
I've created a pull request that solves this.
https://github.com/Nexuist/CoinMarketCapAPI/pull/13

**Comment by altsheets** [comment] 2017-04-27 22:51
Oh wow, NarubyRiverlione, thank you so much.  Open source is so powerful.  
I am now using your repo instead, until @Nexuist is merging your pull request.
Thanks a lot!

**Comment by Nexuist** [comment] 2017-05-14 21:47
Merged. Thank you very much for the help!

**Closed by Nexuist** 2017-05-14 21:47 UTC
